server:
  port: 9999
  servlet:
    session:
      timeout: 30m

spring:
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  datasource:
    url: "jdbc:mysql://localhost:3306/library_management?createDatabaseIfNotExist=true&autoReconnect=true&characterEncoding=UTF-8&allowPublicKeyRetrieval=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Ho_Chi_Minh&useSSL=false"
    username: root
    password: sa
    driver-class-name: "com.mysql.cj.jdbc.Driver"
  jpa:
    database: mysql
    database-platform: "org.hibernate.dialect.MySQL8Dialect"
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
services:
  cloudinary:
    cloud-name: "dfaz1oyc1"
    api-key: "915678887722258"
    api-secret: "1PPbDrkY7Vp5dz0W6691xXvOYL8"